name: keycloak-slickteam-theme
services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./.postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    networks:
      - keycloak-slickteam
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      KC_HTTP_ENABLED: true
    volumes:
      - "./themes/slickteam:/opt/keycloak/themes/slickteam"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false --spi-theme-welcome-theme=slickteam
    networks:
      keycloak-slickteam:
        aliases:
          - keycloak.localhost

volumes:
  postgres-data:

networks:
  keycloak-slickteam:
