services:
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./.tools/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    networks:
      - keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      KC_PROXY: edge
      KC_HOSTNAME: keycloak.localhost
      KC_HOSTNAME_ADMIN: keycloak.localhost
      KC_HTTP_ENABLED: true
    volumes:
      - "./themes/slickteam:/opt/keycloak/themes/slickteam"
    depends_on:
      - postgres
      - traefik
    expose:
      - "8080"
    command: start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false --features="account3,admin-fine-grained-authz,declarative-user-profile"
    labels:
      traefik.enable: "true"
      traefik.http.routers.keycloak.entrypoints: web
      traefik.http.routers.keycloak.tls: "false"
      traefik.http.routers.keycloak.service: keycloak
      traefik.http.services.keycloak.loadbalancer.server.port: 8080
      traefik.http.routers.keycloak.rule: Host(`keycloak.localhost`)
    networks:
      keycloak:
        aliases:
          - keycloak.localhost
  traefik:
    image: traefik:v2.10.4
    hostname: "traefik"
    environment:
      TZ: Europe/Paris
    ports:
      - "80:80"
    volumes:
      - "./test/traefik.yaml:/etc/traefik/traefik.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.entrypoints: web
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.tls: "false"
      traefik.http.routers.traefik.rule: Host(`traefik.localhost`)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - keycloak

volumes:
  postgres-data:

networks:
  keycloak:
    name: keycloak-test